### ISSUE TITLE
Add Labeler CI

### ISSUE THREAD

**Issue by SakulFlee** [SakulFlee/Orbital#411]
> Copied from other project, will need adjustments!

As a GitHub action:

```yaml
name: "Pull Request Labeler"

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Labeler
      uses: actions/labeler@v5
      with:
        dot: true
```

In `.github/labeler.yml`:

```yaml
Godot:
- changed-files:
  - any-glob-to-any-file: 'Godot Project/**'

Server:
- changed-files:
  - any-glob-to-any-file: 'Match Maker Server/**'

CI:
- changed-files:
  - any-glob-to-any-file: '.github/**'
```
